framework:
    html_sanitizer:
        sanitizers:
            app.html_sanitizer:
                allow_safe_elements: false
                allow_relative_links: false
                allow_relative_medias: false
                allow_elements:
                    p: []
                    h1: []
                    h2: []
                    h3: []
                    h4: []
                    h5: []
                    h6: []
                    ul: []
                    ol: []
                    li: []
                    a: ['href', 'title', 'target', 'rel']
                    strong: []
                    em: []
                    b: []
                    i: []
                    br: []
                    blockquote: []
                    code: []
                    pre: []
                    img: ['src', 'alt', 'title', 'width', 'height']
